[workspace]
members = [
  "block-producer",
  "node",
  "proto",
  "rpc",
  "store",
  "utils",
  "test-macro",
]
resolver = "2"

[workspace.dependencies]
miden-crypto = { version = "0.8" }
miden-lib = { package = "miden-lib", git = "https://github.com/0xPolygonMiden/miden-base", branch = "igamigo-test" }
miden-objects = { package = "miden-objects", git = "https://github.com/0xPolygonMiden/miden-base", branch = "igamigo-test" }
miden-tx = { package = "miden-tx", git = "https://github.com/0xPolygonMiden/miden-base", branch = "igamigo-test" }
thiserror = "1.0"
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3", features = [
  "fmt",
  "json",
  "env-filter",
] }
